import asyncio
import re
import io
import zipfile
from agents.backend_code_generator import agent_group_backend;
from agents.frontend_code_generator import agent_group_frontend;

def extract_files_from_agent_output(agent_output: str):
    pattern = re.compile(
        r"### File: ([^\n]+)\n```(?:typescript|html|scss)?\n(.*?)```",
        re.DOTALL | re.MULTILINE
    )
    files = []
    for match in pattern.finditer(agent_output):
        filename = match.group(1).strip()
        code = match.group(2).strip()
        code = re.sub(r'# Code Generated by Sidekick is for learning and experimentation purposes only.\n?', '', code)
        files.append({"path": filename, "code": code})
    return files

def create_zip_in_memory(files):
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        for file in files:
            zip_file.writestr(file["path"], file["code"])
    zip_buffer.seek(0)
    return zip_buffer

async def main():
    agent_grp = agent_group_backend()
    srdDoc = """[YOUR SRD HERE]"""
    task = f"generate Angular code based on the given Frontend SRD document:\n{srdDoc}"

    # Collect all outputs as a string
    all_outputs = ""
    async for message in agent_grp.run_stream(task=task):
        if hasattr(message, "content"):
            all_outputs += str(message.content) + "\n"

    files = extract_files_from_agent_output(all_outputs)
    zip_buffer = create_zip_in_memory(files)

    # Example: Save to disk for testing (remove in production)
    with open("generated_code.zip", "wb") as f:
        f.write(zip_buffer.read())

    # In a web API, you would return zip_buffer.getvalue() as a file response

if __name__ == "__main__":
    asyncio.run(main())
